spring.application.name=CentroDeportivo
# Conexión a Supabase (PostgreSQL)
# Reemplaza [HOST], [PORT], [USER] y [PASSWORD] con los datos de tu proyecto en Supabase
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ujhcclkyxirnbwtomgyn
spring.datasource.password=0093215506Jhon
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# 'update' creará/actualizará las tablas automáticamente basándose en tus @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true